In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
df = pd.read_csv(r"C:\Users\USER\Downloads\apple_quality.csv")

df.head()

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
0,0.0,-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590483,good
1,1.0,-1.195217,-2.839257,3.664059,1.588232,0.853286,0.867530,-0.722809367,good
2,2.0,-0.292024,-1.351282,-1.738429,-0.342616,2.838636,-0.038033,2.621636473,bad
3,3.0,-0.657196,-2.271627,1.324874,-0.097875,3.637970,-3.413761,0.790723217,good
4,4.0,1.364217,-1.296612,-0.384658,-0.553006,3.030874,-1.303849,0.501984036,good


In [57]:
df = df.drop(columns=["A_id"],  errors="ignore")
df["Acidity"] = pd.to_numeric(df["Acidity"], errors="coerce")
df = df.dropna()
df.info(), df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 4000 entries, 0 to 3999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Size         4000 non-null   float64
 1   Weight       4000 non-null   float64
 2   Sweetness    4000 non-null   float64
 3   Crunchiness  4000 non-null   float64
 4   Juiciness    4000 non-null   float64
 5   Ripeness     4000 non-null   float64
 6   Acidity      4000 non-null   float64
 7   Quality      4000 non-null   object 
dtypes: float64(7), object(1)
memory usage: 281.2+ KB


(None,
        Size    Weight  Sweetness  Crunchiness  Juiciness  Ripeness   Acidity  \
 0 -3.970049 -2.512336   5.346330    -1.012009   1.844900  0.329840 -0.491590   
 1 -1.195217 -2.839257   3.664059     1.588232   0.853286  0.867530 -0.722809   
 2 -0.292024 -1.351282  -1.738429    -0.342616   2.838636 -0.038033  2.621636   
 3 -0.657196 -2.271627   1.324874    -0.097875   3.637970 -3.413761  0.790723   
 4  1.364217 -1.296612  -0.384658    -0.553006   3.030874 -1.303849  0.501984   
 
   Quality  
 0    good  
 1    good  
 2     bad  
 3    good  
 4    good  )

In [58]:
X = df.drop(columns=["Quality"])
y = df["Quality"].map({"good": 1, "bad": 0})


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training set size: {X_train.shape[0]} samples")
print(f"Testing set size: {X_test.shape[0]} samples")


Training set size: 3200 samples
Testing set size: 800 samples


In [59]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [60]:
model = LogisticRegression(C = 0.1, max_iter=100, random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [61]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy (C=0.1): {accuracy:.2f}")

print("Classification Report=\n", classification_report(y_test, y_pred))

print("Confusion_Matrix =\n", confusion_matrix(y_test, y_pred))


Accuracy (C=0.1): 0.75
Classification Report=
               precision    recall  f1-score   support

           0       0.75      0.76      0.75       401
           1       0.75      0.75      0.75       399

    accuracy                           0.75       800
   macro avg       0.75      0.75      0.75       800
weighted avg       0.75      0.75      0.75       800

Confusion_Matrix =
 [[303  98]
 [ 99 300]]


In [62]:
model_rf = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
model_rf.fit(X_train, y_train)

# Predict on the test set
y_pred_rf = model_rf.predict(X_test)

# Evaluate the model
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print(f"Accuracy (Random Forest): {accuracy_rf:.2f}")
print("Classification Report:\n", classification_report(y_test, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))

Accuracy (Random Forest): 0.90
Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.89      0.90       401
           1       0.89      0.90      0.90       399

    accuracy                           0.90       800
   macro avg       0.90      0.90      0.90       800
weighted avg       0.90      0.90      0.90       800

Confusion Matrix:
 [[356  45]
 [ 38 361]]


In [63]:
model_svm = SVC(kernel='rbf', random_state=42)

# Train the model
model_svm.fit(X_train, y_train)

# Predict on the test set
y_pred_svm = model_svm.predict(X_test)

# Evaluate the model
accuracy_svm = accuracy_score(y_test, y_pred_svm)
print(f"Accuracy (SVM): {accuracy_svm:.2f}")
print("Classification Report:\n", classification_report(y_test, y_pred_svm))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_svm))

Accuracy (SVM): 0.91
Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.90      0.91       401
           1       0.90      0.91      0.91       399

    accuracy                           0.91       800
   macro avg       0.91      0.91      0.91       800
weighted avg       0.91      0.91      0.91       800

Confusion Matrix:
 [[362  39]
 [ 35 364]]


In [ ]:

# Set up a range of values for C to test
param_grid = {'C': [0.01, 0.1, 1, 10, 100]}

# Create an SVM classifier
svm = SVC(kernel='rbf', random_state=42)

# Use GridSearchCV to find the best C
grid_search = GridSearchCV(svm, param_grid, cv=5, scoring='accuracy')

# Fit the grid search
grid_search.fit(X_train, y_train)

# Best parameter and score
print(f"Best C: {grid_search.best_params_['C']}")
print(f"Best Accuracy: {grid_search.best_score_:.2f}")

# Predict using the best model
best_model = grid_search.best_estimator_
y_pred_best_svm = best_model.predict(X_test)

# Evaluate the best model
accuracy_best_svm = accuracy_score(y_test, y_pred_best_svm)
print(f"Accuracy (Best SVM with adjusted C): {accuracy_best_svm:.2f}")
print("Classification Report:\n", classification_report(y_test, y_pred_best_svm))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_best_svm))


Best C: 100
Best Accuracy: 0.90
Accuracy (Best SVM with adjusted C): 0.93
Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.94      0.93       401
           1       0.93      0.91      0.92       399

    accuracy                           0.93       800
   macro avg       0.93      0.92      0.92       800
weighted avg       0.93      0.93      0.92       800

Confusion Matrix:
 [[375  26]
 [ 34 365]]


In [66]:
model_svm = SVC(kernel='rbf', C = 100, random_state=42)

# Train the model
model_svm.fit(X_train, y_train)

# Predict on the test set
y_pred_svm = model_svm.predict(X_test)

# Evaluate the model
accuracy_svm = accuracy_score(y_test, y_pred_svm)
print(f"Accuracy (SVM with C=100): {accuracy_svm:.2f}")
print("Classification Report:\n", classification_report(y_test, y_pred_svm))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_svm))

Accuracy (SVM with C=100): 0.93
Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.94      0.93       401
           1       0.93      0.91      0.92       399

    accuracy                           0.93       800
   macro avg       0.93      0.92      0.92       800
weighted avg       0.93      0.93      0.92       800

Confusion Matrix:
 [[375  26]
 [ 34 365]]
